config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'about_us', to: 'pages#show', id: 'about_us', as: :about_us

  get 'mi_perfil', to: 'pages#my_profile', as: :my_profile

  patch 'mi_perfil', to: 'pages#update_profile'
  resources :users, only: :destroy

    resources :syllabuses do
    resources :syllabus_modules, controller: 'syllabuses_modules', only: %i[ new create ]
    resources :libraries, only: %i[ create destroy ]
    resources :reviews, only: :create

  end
  resources :syllabus_modules, controller: 'syllabuses_modules', except: %i[ index ] do
    resources :lectures, only: %i[ new create ]
  end
  resources :lectures, except: %i[ new create ] do
    resources :comments
  end
  # resources :comments, only: %i[ edit update destroy ]
  resources :libraries, only: :index

  get "/syllabuses/:id/mentor_profile", to: "syllabuses#mentor_profile", as: :mentor

  #gamificaion
  post 'tasks/complete_task', to: 'tasks#complete_task', as: 'complete_task'
  #post 'tasks/toggle_complete', to: 'tasks#toggle_complete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lecture

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_lecture
  before_action :authenticate_user!

  def index
    # if params[:lecture_id]
    #   @lecture = Lecture.find(params[:lecture_id])
    #   @comments = @lecture.comments
    # else
    #   @comments = Comment.all
    # end
    @lecture = Lecture.find(params[:lecture_id])
    @comments = @lecture.comments.where.not(user_id: nil)
    @comment = @lecture.comments.new
  end


  def new
    @comment = @lecture.comments.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = @lecture.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.turbo_stream
        format.html {redirect_to syllabuses_path}
      end
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @comment = Comment.find(params[:id])
  end


  def update
    @comment = @lecture.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to lecture_comments_path(@lecture), notice: 'Comentario actualizado con éxito.'
    else
      @comments = @lecture.comments
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @comment = Comment.find(params[:id])
    @lecture = @comment.lecture
    @comment.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@comment) }
      format.html { redirect_to syllabuses_path, notice: 'Comentario eliminado con éxito.' }
    end
  end

  private


  def set_lecture
    @lecture = Lecture.find(params[:lecture_id]) if params[:lecture_id]
  end


  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<li class="mb-2">
  <%= turbo_frame_tag dom_id(comment) do %>
    <% if params[:edit_comment_id].to_i == comment.id %>
      <%= simple_form_for [lecture, comment], method: :patch, html: { class: 'w-100 mx-auto' } do |f| %>
        <div class="comment-bubble" style="max-width: 95%; width: 95%; margin: 0 auto; background-color: white; padding: 15px;">
          <div class="card-body">
            <%= f.label :content, "<strong>Edita tu comentario:</strong>".html_safe, class: 'form-label' %>
            <%= f.input :content, as: :text, id: 'comment_content', input_html: { rows: 4, class: 'form-control' }, label: false %>
          </div>
          <div class="comment-footer d-flex justify-content-end" style="background-color: transparent; border-top: none; padding: 0; gap: 0;">
            <button type="submit" class="btn btn-link ms-2" style="margin-right: 0; padding: 0;">
              <i class="fa-solid fas fa-sync fa-lg text-black"></i>
            </button>
            <%= link_to lecture_comments_path(lecture), class: 'btn btn-link' do %>
              <i class="fa-solid fas fa-x fa-lg text-black"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="comment-bubble" <%= 'user-comment' if comment.user == current_user %> shadow-lg" style="max-width: 95%; width: 95%; margin: 10px auto; background-color: white; padding: 15px;">
        <div class="comment-content">
          <p><strong><%= "#{comment.user.first_name} #{comment.user.last_name}" %> </strong> recomendó:</p>
          <p><%= comment.content %></p>
        </div>
        <div class="comment-footer d-flex justify-content-end align-items-center" style="background-color: transparent; border-top: none;">
          <% if comment.user == current_user %>
            <%= link_to lecture_comments_path(lecture, edit_comment_id: comment.id), class: 'me-2' do %>
              <i class="fa-solid fas fa-pen fa-lg text-black"></i>
            <% end %>
            <%= button_to lecture_comment_path(lecture, comment), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'ms-2 trash-icon', form: { data: { turbo_stream: true } } do %>
              <i class="fa-solid fas fa-trash fa-lg text-black"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</li>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments", partial: "comment", locals: { comment: @comment, lecture: @lecture } %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comments", partial: "comment", locals: { comment: @comment, lecture: @lecture } %>

app/views/comments/edit.html.erb
<h3>Editar Comentario</h3>

<%= simple_form_for[@lecture, @comment] do |f| %>
  <%= f.input :content, label: 'Contenido', input_html: { rows: 4, class: "form-control" } %>

  <div class="form-group">
    <%= f.button :submit, 'Actualizar Comentario', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/index.html.erb
<%= turbo_frame_tag :comment do %>
  <% if @lecture %>
    <% if @comments.any? %>
      <ul id="comments" class="list-unstyled mt-1">
        <% @comments.each do |comment| %>
          <%= render "comment", comment: comment, lecture: @lecture, user: current_user %>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center mt-4">No hay comentarios para esta lección aún.</p>
    <% end %>
  <% else %>
    <p class="text-center">No se ha seleccionado ninguna lección.</p>
  <% end %>

  <%= turbo_frame_tag :new_comment_form do %>
    <%= simple_form_for [@lecture, @comment], html: { data: { controller: "reset-comments", action: "turbo:submit-end->reset-comments#reset"}, class: 'w-100 mx-auto' } do |f| %>
      <div class="comment-bubble" style="max-width: 95%; width: 95%; margin: 0 auto; background-color: white; padding: 10px;">
        <div class="card-body">
          <%= f.label :content, "<strong>Escribe tu comentario:</strong>".html_safe, class: 'form-label' %>
          <%= f.input :content, as: :text, input_html: { rows: 4, class: 'form-control', id: "comment_content" }, label: false %>
        </div>
        <div class="comment-footer text-center" style="background-color: transparent; border-top: none;">
          <%= f.submit "Comentar", class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<h3 class="text-center mt-5 mb-5">Nuevo Comentario</h3>

<%= simple_form_for [ @lecture, @comment ], html: { class: 'w-50 mx-auto' } do |f| %>
  <div class="card shadow-sm p-3 mb-5">
    <div class="card-body">
      <%= f.label :content, "Escribe tu comentario:", class: 'form-label' %>
      <%= f.input :content, as: :text, input_html: { rows: 4, class: 'form-control' }, label: false %>
    </div>
    <div class="card-footer text-end">
      <%= f.submit "Comentar", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<%# http://127.0.0.1:3000/lectures/1/comments/new %>

app/views/comments/show.html.erb
<div class="container mt-5 mb-5">git 
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-header bg-light">
          <h3>Detalles del Comentario</h3>
        </div>
        <div class="card-body">
          <p class="card-text"><strong>Comentario:</strong> <%= @comment.content %></p>

          <div class="d-flex justify-content-between mt-3">
            <%= link_to 'Volver a la Clase', lecture_path(@comment.lecture), class: "btn btn-primary" %>
            <%= link_to 'Editar Comentario', edit_comment_path(@comment), class: "btn btn-primary" %>
            <%= button_to 'Eliminar Comentario', comment_path(@comment), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%# # http://127.0.0.1:3000/comments/2/ %>