config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'about_us', to: 'pages#show', id: 'about_us', as: :about_us

  get 'mi_perfil', to: 'pages#my_profile', as: :my_profile

  patch 'mi_perfil', to: 'pages#update_profile'
  resources :users, only: :destroy

    resources :syllabuses do
    resources :syllabus_modules, controller: 'syllabuses_modules', only: %i[ new create ]
    resources :libraries, only: %i[ create destroy ]
    resources :reviews, only: :create

  end
  resources :syllabus_modules, controller: 'syllabuses_modules', except: %i[ index ] do
    resources :lectures, only: %i[ new create ]
  end
  resources :lectures, except: %i[ new create ] do
    resources :comments
  end
  # resources :comments, only: %i[ edit update destroy ]
  resources :libraries, only: :index

  get "/syllabuses/:id/mentor_profile", to: "syllabuses#mentor_profile", as: :mentor

  #gamificaion
  post 'tasks/complete_task', to: 'tasks#complete_task', as: 'complete_task'
  #post 'tasks/toggle_complete', to: 'tasks#toggle_complete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController
  before_action :set_syllabus, only: %i[show edit update destroy mentor_profile]

  def index
    @categories = Category.all
    @syllabuses = Syllabus.all

    # Filtramos por categoría si está presente
    @syllabuses = @syllabuses.where(category: params[:category]) if params[:category].present?

    # Lógica para la búsqueda
    if params[:query].present?
      query = "%#{params[:query]}%"
      @categories = @categories.where("name ILIKE ?", query)
      @syllabuses = @syllabuses.where("title ILIKE ?", query)
      @syllabuses_modules = SyllabusModule.where("name ILIKE ?", query)
      @lectures = Lecture.where("details ILIKE ?", query)
    end
  end


  def new
    @syllabus = Syllabus.new
  end

  def create
    @syllabus = Syllabus.new(syllabus_params)
    @syllabus.user = current_user
    if @syllabus.save
      redirect_to syllabus_path(@syllabus), notice: 'Syllabus fue exitosamente creado.'

    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

    @syllabus = Syllabus.includes(syllabus_modules: :lectures).find(params[:id])

    @syllabus = Syllabus.includes(syllabus_modules: :lectures).find(params[:id])
    @review = Review.new
  #cargar también módulos o bibliotecas asociadas
  @modules = @syllabus.syllabus_modules
  @libraries = @syllabus.libraries
  @user = current_user
  @mentor = Syllabus.find_by(user_id:@syllabus.user_id)

  @syllabus = Syllabus.includes(syllabus_modules: :lectures).find(params[:id])

  total_lectures = @syllabus.syllabus_modules.sum { |mod| mod.lectures.count }
  completed_lectures = session[:completed_lectures].to_a.count
  @progress_percentage = total_lectures > 0 ? (completed_lectures.to_f / total_lectures * 100).round : 0
end

  def edit
  end

  def update
    if @syllabus.update(syllabus_params)
      redirect_to @syllabus, notice: 'Syllabus exitosamente actualizado.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @syllabus.destroy
    redirect_to libraries_path, notice: 'Syllabus exitosamente borrado.'
  end

  def mentor_profile
    @mentor = Syllabus.find_by(user_id:@syllabus.user_id)
  end

  private

  def set_syllabus
    @syllabus = Syllabus.find(params[:id])
  end

  def syllabus_params
    params.require(:syllabus).permit(:title, :category_id, :description, :image)
  end
end

app/views/syllabuses/edit.html.erb
<div class="custom-card-new rounded-5 bg-light">
  <%= simple_form_for(@syllabus, html: { class: 'container my-5', style: 'max-width: 600px;' }) do |f| %>

    <% if @syllabus.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h4><%= pluralize(@syllabus.errors.count, "error") %> prohibited this syllabus from being saved:</h4>
        <ul>
          <% @syllabus.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Título del formulario -->
    <div class="form-group">
      <%= f.input :title, label: 'Title', input_html: { class: 'form-control' } %>
    </div>

    <!-- Descripción del formulario -->
    <div class="form-group">
      <%= f.input :description, label: 'Description', as: :text, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.association :category, label: 'Categoría', input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.input :image, label: 'Fotografía', as: :file, input_html: { class: 'form-control' } %>
    </div>

  <div class= "d-flex m-3 justify-content-center">
    <!-- Botón de envío -->
    <div class="form-actions text-center m-3">
      <%= f.button :submit, 'Guardar Cambios', class: 'btn btn-primary' %>
    </div>

    <div class="form-actions text-center m-3">
      <%= f.button :submit, 'Editar Contenido', class: 'btn btn-danger' %>
    </div>
  </div>
  <% end %>
</div>

app/views/syllabuses/index.html.erb
<h1 class="text-center mt-5 fw-bold">Syllabus que tenemos para tí</h1>

<div class="container my-5 container-width">
  <div class="row g-4">
    <% @categories.each do |category| %>
      <div class="col-md-4 mb-4">
        <div class="list-group shadow-sm rounded">
          <div class="list-group-item py-3 bg-primary text-white text-center category-title black">
            <h5 class="mb-1 text-truncate fw-bold"><%= category.name %></h5>
          </div>
          <%= image_tag "categorias/#{category.name}.jpg", class: "img-category" %>
          <% category_syllabuses = Syllabus.where(category_id: category.id) %>
          <% category_syllabuses.each do |syllabus| %>
            <div class="syllabus-card">
              <%= link_to syllabus_path(syllabus), class: 'text-dark text-decoration-none' do %>
                <div class="list-group-item d-flex justify-content-between align-items-center py-3 syllabus-item">
                  <div class="d-block">
                    <h5 class="mb-1 text-center"><strong><%= syllabus.title %></strong></h5>
                    <small><%= syllabus.description.first(90) %>...</small>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Estilos específicos para las imágenes, tarjetas y títulos -->
<style>
  .container.my-5 {
    margin-top: 3rem; /* Margen superior */
    margin-bottom: 3rem; /* Margen inferior */
    font-family: 'Inter', sans-serif !important;
  }

  .img-category {
    width: 100%; /* Ajusta el ancho al contenedor */
    height: 250px; /* Más alargada */
    object-fit: cover; /* Recorta la imagen para llenar el espacio sin distorsión */
    border-radius: 8px; /* Bordes redondeados */
    margin-bottom: 10px; /* Espaciado inferior entre la imagen y el contenido */
  }

  .list-group {
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Sombra para las tarjetas */
    border-radius: 8px; /* Bordes redondeados para las tarjetas */
    overflow: hidden;
    font-family: 'Inter', sans-serif !important;
  }

  .list-group-item:first-child {
    border-top-left-radius: 8px; /* Bordes redondeados superiores */
    border-top-right-radius: 8px;
  }

  .category-title {
    text-align: center; /* Centra el texto del título */
    font-weight: bold; /* Destaca el texto */
    font-family: 'Inter', sans-serif !important;
  }

  /* Asegura que los sílabos tengan el mismo tamaño */
/* Estilo para el syllabus */
.syllabus-item {
  height: 200px; /* Ajusta el tamaño como lo necesites */
  overflow: hidden;
  position: relative; /* Necesario para posicionar el icono encima del contenido */
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s ease; /* Transición suave */
}

/* Efecto hover: el blur afecta solo al contenido, no al icono */
.syllabus-card:hover .syllabus-item .syllabus-content {
  filter: blur(5px); /* Aplica el blur solo al contenido */
  transition: filter 0.3s ease; /* Transición suave para el blur */
}

/* Icono de ojo sobre el syllabus */
.syllabus-card:hover .syllabus-item::before {
  content: '\f06e'; /* Código Unicode para el ícono de ojo (Font Awesome) */
  font-family: 'Font Awesome 5 Free'; /* Asegúrate de usar la familia de Font Awesome */
  font-weight: 900; /* Necesario para mostrar los iconos de Font Awesome */
  font-size: 50px; /* Tamaño del icono */
  color: black; /* Color del icono */
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 2; /* Asegura que el icono esté por encima del contenido */
  pointer-events: none; /* El icono no interfiere con los clics */
}

/* Desaparecer el contenido del syllabus cuando se pasa el ratón */
.syllabus-card:hover .syllabus-item .syllabus-content {
  opacity: 0; /* Hace desaparecer el contenido cuando se pasa el ratón */
}

/* Asegurarse de que el contenido no se vea después del hover */
.syllabus-content {
  transition: opacity 0.3s ease;
}

/* Estilo adicional para las imágenes si es necesario */
.img-category {
  width: 100%;
  height: 200px;
  object-fit: cover; /* Asegura que las imágenes se ajusten bien al espacio */
  border-radius: 10px;
}

</style>

app/views/syllabuses/mentor_profile.html.erb
<%= render "pages/mentor_profile", mentor: @mentor %>

app/views/syllabuses/new.html.erb
<div class="custom-card-new rounded-5 bg-light">
  <h1 class="display-4 text-center mt-5 fw-bold">Crea un Syllabus</h1>

  <%= simple_form_for(@syllabus, html: { class: 'container my-5', style: 'max-width: 600px;' }) do |f| %>

    <% if @syllabus.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h4><%= pluralize(@syllabus.errors.count, "error") %> prohibited this syllabus from being saved:</h4>
        <ul>
          <% @syllabus.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Título del formulario -->
    <div class="form-group">
      <%= f.input :title, label: 'Título', input_html: { class: 'form-control' } %>
    </div>

      <div class="form-group">
      <%= f.input :description, label: 'Descripción', as: :text, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.association :category, label: 'Categoría', input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.input :image, label: 'Fotografía', as: :file, input_html: { class: 'form-control' } %>
    </div>

    <!-- Botón de envío -->
    <div class="form-actions text-center mt-5">
      <%= f.button :submit, 'Crear un Syllabus', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/syllabuses/show.html.erb
<div class="container mt-5">
  <div>
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active white-box" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Detalles</button>
        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Contenido</button>
      </div>
    </nav>
    <div class="tab-content mt-5" id="nav-tabContent">
      <div class="tab-pane fade show active mt-5" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
        <div class="row">
          <div class="col-md-12 text-center mb-4">
            <%= cl_image_tag(@syllabus.image.key, width: 800, height: 400, crop: :fill, class: "img-fluid rounded-4 shadow-lg border border-muted mb-4") if @syllabus.image.present? %>
          </div>
          <div class="col-md-12">
            <h1 class="text-black text-center font-weight-bold mb-4">
              <%= @syllabus.title %>
            </h1>
            <p class="text-black mb-3" style="text-align: justify;">
              <%= @syllabus.description %>
            </p>
            <p class="font-weight-bold text-dark mb-3">
              Categoría: <span class="text-muted"><strong><%= @syllabus.category.name %></strong></span>
            </p>
            <p class="font-weight-bold text-dark mb-3">
              Mentor: <span class="text-muted"><strong><%= link_to "#{@syllabus.user.first_name} #{@syllabus.user.last_name}", mentor_path(@syllabus), data: {turbo_frame: :mentor_profile} %></strong></span>
            </p>
            <p class="font-weight-bold text-dark mb-3">
              Puntuación:
              <span class="rating">
                <% if @syllabus.reviews.size > 0 %>
                  <% average_rating = (@syllabus.reviews.map(&:rating).sum / @syllabus.reviews.size.to_f).round(2) %>
                <% else %>
                  <% average_rating = 0 %>
                <% end %>
                <% full_stars = average_rating.to_i %>
                <% half_star = (average_rating - full_stars) >= 0.5 ? 1 : 0 %>
                <% empty_stars = 5 - full_stars - half_star %>
                <% full_stars.times do %>
                  <i class="fa fa-star text-warning"></i>
                <% end %>
                <% half_star.times do %>
                  <i class="fa fa-star-half-alt text-warning"></i>
                <% end %>
                <% empty_stars.times do %>
                  <i class="fa fa-star text-muted"></i>
                <% end %>
                <strong><%= average_rating %> / 5</strong>
              </span>
            </p>
          </div>
        </div>
        <hr>
        <div class="mt-5">
          <%= turbo_frame_tag :mentor_profile %>
        </div>
      </div>

      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
        <div class="container">
            <h1 class="text-black text-center font-weight-bold mb-4">
              <%= @syllabus.title %>
            </h1>
          <div class="progress mt-3 mb-5">
            <div class="progress-bar bg-success" role="progressbar" style="width: <%= @progress_percentage %>%;" aria-valuenow="<%= @progress_percentage %>" aria-valuemin="0" aria-valuemax="100">
              <%= @progress_percentage %>% completado
            </div>
          </div><%= link_to "Agregar Módulo", new_syllabus_syllabus_module_path(@syllabus), data: {turbo_frame: :syllabus_module}, class: "btn btn-primary m-2" if current_user.id == @syllabus.user_id %>
          <%= turbo_frame_tag :syllabus_module %>
            <div class="row">
            <div class="col-8">
              <div class="accordion" id="modulesAccordion">
                <% @syllabus.syllabus_modules.each_with_index do |modulo, index| %>
                  <%= render "syllabuses_modules/syllabuses_modules", modulo:, index: %>
                <% end %>
              </div>
            </div>
            <div class="col-4">
              <%= turbo_frame_tag :comment %>
            </div>
          </div>
          <div class="position-fixed bottom-0 start-0 mb-3 ms-3" style="width: 300px; padding: 10px;">
            <div class="card shadow-sm p-2 bg-white text-dark rounded-3" style="max-width: 100%; min-width: 300px; border: 1px solid #ddd;">
              <div class="card-body">
                <%= simple_form_for [@syllabus, @review], data: { controller: "submit" } do |f| %>
                  <div class="d-flex align-items-center mb-3">
                    <%= f.input :rating, label: "¿Qué te pareció este Syllabus?", collection: (1..5).to_a, input_html: { data: { controller: "star-rating", action: "click->form-submit#submit" }, class: "star-rating-input" }, label_html: { style: 'font-weight: bold; font-size: 1rem; margin-right: 10px;' }, required: false %>
                  </div>
                  <div class="d-flex justify-content-center">
                    <%= f.submit "Enviar", class: "btn btn-primary btn-sm" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="text-center mt-5 mb-5">
  <%= button_to "Agregar a mi Biblioteca", syllabus_libraries_path(@syllabus), method: :post, class: 'btn btn-primary btn-lg' unless current_user.id == @syllabus.user_id %>
</div>