config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'about_us', to: 'pages#show', id: 'about_us', as: :about_us

  get 'mi_perfil', to: 'pages#my_profile', as: :my_profile

  patch 'mi_perfil', to: 'pages#update_profile'
  resources :users, only: :destroy

    resources :syllabuses do
    resources :syllabus_modules, controller: 'syllabuses_modules', only: %i[ new create ]
    resources :libraries, only: %i[ create destroy ]
    resources :reviews, only: :create

  end
  resources :syllabus_modules, controller: 'syllabuses_modules', except: %i[ index ] do
    resources :lectures, only: %i[ new create ]
  end
  resources :lectures, except: %i[ new create ] do
    resources :comments
  end
  # resources :comments, only: %i[ edit update destroy ]
  resources :libraries, only: :index

  get "/syllabuses/:id/mentor_profile", to: "syllabuses#mentor_profile", as: :mentor

  #gamificaion
  post 'tasks/complete_task', to: 'tasks#complete_task', as: 'complete_task'
  #post 'tasks/toggle_complete', to: 'tasks#toggle_complete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  belongs_to :syllabus

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def index
    @libraries = current_user.libraries
  end

  def show
    @library = Library.find(params[:id])
  end

  def create
    syllabus = Syllabus.find(params[:syllabus_id])
    library = current_user.libraries.new(syllabus: syllabus)
    if library.save
      redirect_to libraries_path, notice: "La biblioteca fue creada con éxito.."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @library = Library.find(params[:id])
    @library.destroy
    redirect_to libraries_url, notice: "La biblioteca fue destruida con éxito."
  end

  private

  def library_params
    params.require(:library).permit(:user_id, :syllabus_id)
  end

end

app/views/libraries/index.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col-12">
      <h2 class="mt-5 mb-5 text-center">Mi Biblioteca</h2>
    </div>
  </div>

  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Estudiante</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Mentor</button>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active text-black" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
      <div class="row mb-5">
        <% @libraries.each do |library| %>
          <div class="col-12 col-md-4 mb-4 mt-5">
            <div class="custom-card-vertical rounded-5 bg-light">
              <%= cl_image_tag library.syllabus.image.key, class: "card-image" if library.syllabus.image.attached? %>
              <div class="card-body d-flex flex-column">
                <h3 class="card-title text-center"><%= library.syllabus.title %></h3>
                <p class="card-subtitle">Mentor: <strong><%= "#{library.syllabus.user.first_name} #{library.syllabus.user.last_name}" %></strong></p>
                <p class="text-center card-text"><%= library.syllabus.description.first(250)%>...</p>
                <div class="d-flex justify-content-end gap-3" style="position: absolute; bottom: 10px; right: 10px;">
                  <%= link_to syllabus_path(library.syllabus) do %>
                    <i class="fa-solid fas fa-eye fa-lg text-black"></i>
                  <% end %>
                  <%= button_to syllabus_library_path(library.syllabus, library), method: :delete do %>
                    <i class="fa-solid fas fa-trash fa-lg text-black"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
      <div class="text-center m-1">
        <%= link_to 'Agregar Syllabus', new_syllabus_path, class: 'btn btn-primary btn-lg mt-5' %>
      </div>
      <div class="row mb-5">
        <% current_user.syllabuses.each do |syllabus| %>
          <div class="col-12 col-md-4 mb-4 mt-5">
            <div class="custom-card-vertical rounded-5 bg-light">
              <%= cl_image_tag syllabus.image.key, class: "card-image" if syllabus.image.attached? %>
              <div class="card-body d-flex flex-column">
                <h3 class="card-title text-center"><%= syllabus.title %></h3>
                <p class="card-subtitle">Mentor: <strong><%= "#{syllabus.user.first_name} #{syllabus.user.last_name}" %></strong></p>
                <p class="card-subtitle">Category: <strong><%= syllabus.category.name %></strong></p>
                <p class="text-center card-text"><%= syllabus.description.first(180) %>...</p>
                <div class="d-flex justify-content-end gap-3" style="position: absolute; bottom: 10px; right: 10px;">
                  <%= link_to syllabus_path(syllabus) do %>
                    <i class="fa-solid fas fa-eye fa-lg text-black"></i>
                  <% end %>
                  <%= button_to syllabus_path(syllabus), method: :delete do %>
                    <i class="fa-solid fas fa-trash fa-lg text-black"></i>
                  <% end %>
                  <%= link_to edit_syllabus_path(syllabus) do %>
                    <i class="fa-solid fas fa-pen fa-lg text-black"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>